# For a list of available cops see:
# https://github.com/bbatsov/rubocop/blob/master/config/default.yml
AllCops:
  TargetRubyVersion:
    2.5

Style/Documentation:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

